// SPDX-License-Identifier: Apache-2.0

plugins {
    alias(libs.plugins.kotlinMultiplatform) apply false
    alias(libs.plugins.testBalloon) apply false
    alias(libs.plugins.detekt) apply false
    alias(libs.plugins.spotless) apply false
    alias(libs.plugins.axionRelease)
}

// Git-tag-driven versioning. With no release tags yet, axion derives 0.1.0-SNAPSHOT
// (0.1.0 is axion's default initial version). The release workflow passes the increment
// strategy via -PversionIncrement (incrementPatch | incrementMinor | incrementMajor).
scmVersion {
    versionIncrementer((project.findProperty("versionIncrement") ?: "incrementMinor").toString())
}

group = "io.cloudevents"
version = scmVersion.version

// Single entry point that forces resolution of every resolvable configuration across all
// projects — the plugin classpath, every KMP target's compile/runtime/metadata graph (all
// klibs), and the test dependencies. Dependency verification metadata is generated by running
// `--write-verification-metadata sha256` against this task, and the CI cross-check re-runs it
// with `--refresh-dependencies --dry-run` to detect drift from Maven Central. Resolution is
// lenient so a configuration that cannot resolve on the current host does not abort the sweep.
tasks.register("resolveAllDependencies") {
    val projectConfigurations = allprojects.map { it.configurations }
    doLast {
        projectConfigurations.forEach { configurations ->
            configurations
                .filter { it.isCanBeResolved }
                .forEach { configuration ->
                    runCatching { configuration.incoming.artifactView { isLenient = true }.files.count() }
                }
        }
    }
}
